# Generated by Django 3.0 on 2021-05-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkupapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='userdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkupapp.UserDetail'),
        ),
    ]
